service: serverless-cognito-react-app

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1
  profile: personal_serverless

functions:
  createJob:
    handler: api/handlers/job.create
    events: 
      - http:
          path: job/create 
          method: get
          cors: true 

# you can add packaging information here
package:
  exclude:
    - app/**

resources:
  Resources:
    appUserPool:
      Type: 'AWS::Cognito::UserPool'
      Properties:
        UserPoolName: app-user-pool
    reactAppClient:
      Type: 'AWS::Cognito::UserPoolClient'
      Properties:
        ClientName: react-app-client
        GenerateSecret: false
        UserPoolId: 
          Ref: appUserPool
  Outputs:
    userPoolId:
      Value:
        Ref: appUserPool
    userPoolWebClientId:
      Value:
        Ref: reactAppClient